# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.plymouth = {
    enable = true;
    theme = "catppuccin-macchiato";
    themePackages = [
      pkgs.catppuccin-plymouth
    ];
  };
  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "cryptd" "dm-crypt" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  # raid 1 btrfs disks
  # https://nixos.wiki/wiki/Full_Disk_Encryption
  # TODO: move / to these disks temporarily then luks encrypt the next
  boot.initrd.luks.devices = {
    raider0 = { device = "/dev/disk/by-label/raider0"; };
    raider1 = { device = "/dev/disk/by-label/raider1"; };
  };
  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/ab7aa4e1-c45c-4267-be12-181ebccabfa1";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/home/raider" =
    {
      device = "/dev/mapper/raider0";
      fsType = "btrfs";
      options = [ "nofail" "noatime" ];
      # options = [ "nofail" "uid=1000" "gid=1000"];
      depends = [ "/" ];
    };
  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/760E-DB56";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp42s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
