# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.plymouth = {
    enable = false;
    theme = "catppuccin-macchiato";
    themePackages = [
      pkgs.catppuccin-plymouth
    ];
  };
  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "cryptd" "dm-crypt" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  # raid 1 btrfs disks
  # https://nixos.wiki/wiki/Full_Disk_Encryption
  # TODO: move / to these disks temporarily then luks encrypt the next
  boot.initrd.luks.devices = {
    raider0 = { device = "/dev/disk/by-label/raider0"; };
    raider1 = { device = "/dev/disk/by-label/raider1"; };
    burro = { device = "/dev/disk/by-label/burro"; };
  };
  fileSystems."/" =
    {
      device = "/dev/mapper/burro";
      fsType = "btrfs";
      options = [ "subvol=/" "noatime" ];
    };

  fileSystems."/home/raider" =
    {
      device = "/dev/mapper/raider0";
      fsType = "btrfs";
      options = [ "nofail" "noatime" ];
      depends = [ "/" ];
    };
  fileSystems."/boot" =
    {
      device = "/dev/disk/by-label/STIVALE";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp42s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
